# Generated by Django 4.2.7 on 2023-11-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=250)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Stansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stansiya_nomi', models.CharField(max_length=250)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.tuman')),
            ],
        ),
        migrations.CreateModel(
            name='Osimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osimlik_nomi', models.CharField(max_length=250)),
                ('stansiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.stansiya')),
            ],
        ),
        migrations.CreateModel(
            name='Hashorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashorot_nomi', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('osimlik_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.osimlik')),
            ],
        ),
        migrations.CreateModel(
            name='DataHashorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osimlik_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.osimlik')),
                ('stansiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.stansiya')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.tuman')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.viloyat')),
            ],
        ),
    ]
